bundle: kubernetes
applications:
  istio-gateway:
    charm: istio-gateway
    channel: 1.11/stable
    scale: 1
    options:
      gateway_service_type: NodePort
      kind: ingress
  istio-pilot:
    charm: istio-pilot
    channel: 1.11/stable
    scale: 1
    options:
      default-gateway: kubeflow-gateway
  seldon-controller-manager:
    charm: seldon-core
    channel: 1.14/stable
    scale: 1
  minio:
    charm: minio
    channel: ckf-1.6/stable
    scale: 1
    options:
      mode: gateway
      gateway-storage-service: azure
      access-key: include-file://./secrets/access-key.secret
      secret-key: include-file://./secrets/secret-key.secret
relations:
- - istio-pilot:istio-pilot
  - istio-gateway:istio-pilot